
times:
   element: 0.25
   before_relation: 0.25
   relation: 0.25
   after_relation: 0.25
   after_pair: [2, 2.5]
   after_last_pair: [3, 3.5]
   time_to_respond: 2

sizes:
   letter: 2.5
   fix_height: 0.25
   fix_width: 0.1

fix_shape: 'circle'
fix_between_pairs: True
fix_during_wait: True