
times:
   element: 0.25
   before_relation: 0.25
   relation: 0.25
   after_relation: 0.25
   after_pair: [2, 2.5]
   after_last_pair: [3, 3.5]
   response: 2

sizes:
   letter: 2.5
   fix_height: 0.25
   fix_width: 0.1

fix_shape: 'circle'
fix_between_pairs: True
fix_during_wait: True

# keys for yes/no (mapping is randomized)
resp_keys: [f, j]

przerwa_co_ile_modeli: 1
tekst_przerwy: Czas na przerwę - jeżeli masz taką potrzebę. Możesz teraz mrugać i ruszać się do woli. Aby przejść dalej naciśnij dowolny klawisz.

quit:
   enable: True
   button: q