send_triggers: True
port_adress: '0xCC00'
triggers:
   fixation: [11, 12] # one trigger for normal, other for highlight
   letter: 1
   relation: 2
   question_add: 2
   question_mark: 5

present_sequential: True
reverse_question_relation: False
elem_x_pos: [-2.5, 0, 2.5, 5]

# only element time is used if presentation is not sequential
# before_relation, relation and after_relation are not used
# then
times:
   pre_pair: [0.6, 1.2]
   element: 0.75
   before_relation: 0.25
   relation: 0.75
   after_relation: 0.25
   after_pair: [0.6, 1.2]
   after_last_pair: [4.5, 5.5]
   after_last_question: [1.5, 2.5]
   fix_highlights: [0.5, 1.]
   pre_question_mark: 0.1
   question_mark: 0.2
   response: 5

sizes:
   letter: 5
   fix_height: 0.5
   fix_width: 0.1
   key_info: 1.5
feedback_circle_radius: 7

fix_shape: 'circle'
fix_between_pairs: True
fix_during_wait: True
fix_change_color: [191, 30, 45]

isoluminant_relations: False
iso_degs: [135, 315]

# keys for yes/no (mapping is randomized)
resp_keys: [f, j]

# wybór triali
# ------------
training_trials: 2
# repetitions mówi o tym ile razy bierzemy podstawowe kombinacje
# jeżeli używamy 2 trudności * 2 kolejności modeli
# a do każdego mamy 3 odległości pytań * 2 czyodwrócona relacja * 2 czyodpowiedź tak
# to mamy 4 warunki a do każdego 4 pakiety pytań (po 3)
# w związku z tym mamy 4 * 4 = 16 kombinacji warunek - pytania
# te wartość mnożymy przez repetitions i mamy docelową liczbę triali
repetitions: 15
condition_rows: [0, 2] # tzn pierwszy i trzeci rząd (czyli bez środkowych)
condition_columns: [0] # [0, 1] - obie sekwencje dla każdego warunku

przerwa_co_ile_modeli: 1
tekst_przerwy: Czas na przerwę - jeżeli masz taką potrzebę.\nMożesz teraz mrugać i ruszać się do woli.\nAby przejść dalej naciśnij dowolny klawisz.

quit:
   enable: True
   button: q